### ISSUE TITLE
Our package name is scooped!

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/biobalm#114]
It appears someone has registered the `balm` package name on pypi but not released anything. We can only see the package on test.pypi, which we did not check (the github repo is private): https://test.pypi.org/project/balm/

It looks like it was last updated last August. We can try to contact the author, or we can change the name. Suggestions?

**Comment by jcrozum** [comment]
P.S. as far as I can tell, there is no good way to check name availability in advance, because that would run counter to PyPI's goals of giving me a migraine.

**Comment by daemontus** [comment]
Damn :D And by a Cornell professor! I'll write him an email to ask if he's going to use it. Maybe we can have it if it isn't some secret cool project that will be released soon.

**Comment by jcrozum** [comment]
In the worst case, we can do some simple renaming, e.g., `map->diagram = bald`

**Comment by giang-trinh** [comment]
Yes. While waiting for the response, I will think about a new name for our project.

**Comment by giang-trinh** [comment]
> In the worst case, we can do some simple renaming, e.g., `map->diagram = bald`

The name "bald" recalled me this article <https://neurosciencenews.com/bladness-protein-21115/>. :)

**Comment by daemontus** [comment]
So, we've got a response :) 

Unfortunately, we'll have to find another name :/ The `balm` name will be used and the project is now live https://github.com/itrummer/balm

I'm fine with BoALM, but we can try to compile a list of options for the next meeting. We could also consider `balm-bn` (biological attractor landscape mapper for boolean networks).

**Comment by jcrozum** [comment]
We're `biobalm` now. I'll change the repo name soon.

**Comment by jcrozum** [comment]
done!
