### ISSUE TITLE
Write "Partial Succession Diagrams"

### ISSUE THREAD

**Issue by daemontus** [jcrozum/biobalm#59]
See #55 for context.

This sub-section should define "full" succession diagrams and the notion of a "partially expanded" (or "partial" for short) succession diagram.

Basically, the idea is that such "partial" diagram must have nodes corresponding to all minimal trap spaces and all such nodes are reachable from the root, but it can have nodes that are not expanded, and as such have no outgoing edges ("stubs").

The question right now is whether these "stub" nodes should have some "fast-forward" edges that lead to the largest fully-expanded node which is their proper subspace. This might be useful for things like control (it is immediately obvious what are the reachable trap spaces, and by transition attractors (mostly), of a specific stub node), but complicates things slightly because it introduces another special type of edge. Furthermore, for the purposes of control, this information can be easily computed by the actual control algorithm (instead of tracking this inside the diagram).

**Comment by jcrozum** [comment]
This was done, I believe, but will need to be modified for the new block expansion.

**Comment by daemontus** [comment]
Closing as essentially completed.
