### ISSUE TITLE
Compute attractors and SDs of real-world networks

### ISSUE THREAD

**Issue by daemontus** [jcrozum/biobalm#61]
We already have all the real-world models and an implementation that seems to work reasonably well on them. Which means we can start computing preliminary results.

The core issue is that right now, we only test one input combination for each model. In many cases, this does not really matter. However, there are models where this causes drastic differences in attractors.

The goal of this issue is to compute the succession diagram and attractors for as many input combinations as possible (for many networks, we can just enumerate all of them, for some we'll need to sample randomly).

Ideally, we should actually save the results somewhere. So the goal is to also figure out how to print the succession diagram in some sensible way. For the actual attractors, if we only have a single "seed" state, we can print that. If we have the larger symbolic set, we can dump the whole BDD (AEON supports this). The advantage is that we don't have to recompute the attractors ever again once we have these somewhere.

**Comment by jcrozum** [comment]
@daemontus It looks like this is being tracked in the `balm-analysis` repo. Can we resolve it here?

**Comment by daemontus** [comment]
Yeah, I think we can close this and just treat the `balm-analysis` repo as the new place where these things are happening. (I don't see anything that meaningful in the issue description anyway)
