### ISSUE TITLE
Meta analysis of update functions in BBM real-world networks

### ISSUE THREAD

**Issue by daemontus** [jcrozum/biobalm#65]
In particular, we want to know how common are:
 - threshold functions
 - nested canalising functions
 
The problem is that we probably shouldn't use syntax for this, because the function expressions can be very weird depending on format. So we actually need some more sophisticated method (this should be a fast test with on the BDD representation once we figure out the right conditions, but maybe there is an easier way to test this even if it takes more time to run it).

**Comment by jcrozum** [comment]
I'm going to close this as being out-of-scope for the current manuscript.
